#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int countValue = 0;

	nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[motorC] = mtrSpeedReg;
	while(1 == 1)
	{
		if (SensorValue(lightSensor) < 40)
		{
			motor[motorB] = 50;
			motor[motorC] = 50;
			countValue = countValue + 1;
		}
	}
}
