#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(1 == 1)
  {
  	//robot moves at half speed
		motor[motorB] = 50;
		motor[motorC] = 50;

		while(SensorValue (lightSensor) <= 40)
		{
 //robot stops
			motor[motorB] = 0;
			motor[motorC] = 0;

		}//end while
	}//end while

}
